name: banca_movil
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  animations: ^2.0.11
  bcrypt: ^1.1.3
  crypto: ^3.0.6
  encrypt: ^5.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_secure_storage: ^9.2.4
  go_router: ^16.2.1
  go_transitions: ^0.8.2
  icons_plus: ^5.0.0
  lottie: ^3.3.2
  path_provider: ^2.1.5
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

scripts:
  make:model: "dart run lib/scripts/generate_model.dart"
  make:controller: "dart run lib/scripts/generate_controller.dart"
  make:view: "dart run lib/scripts/generate_view.dart"
  make:mvc: "dart run lib/scripts/generate.dart"

flutter:
  uses-material-design: true
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter_variable.ttf
    - family: OpenSans
      fonts:
        - asset: assets/fonts/opensans_variable.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat_variable.ttf
    - family: NotoSans
      fonts:
        - asset: assets/fonts/notosans_variable.ttf
  assets:
    - assets/lottie/
    # - assets/icons/
